var ometajs = require('ometajs'),
    OMeta = ometajs.OMeta;
{var CSSBSParser=exports.CSSBSParser=objectThatDelegatesTo(OMeta,{
"ident":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("m_ident");return ["ident",x]}).call(this)},
"atkeyword":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","@");x=this._apply("m_ident");return ["atkeyword",x]}).call(this)},
"string":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("m_string");return ["string",x]}).call(this)},
"hash":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","#");x=this._apply("m_name");return ["hash",x]}).call(this)},
"number":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("m_number");return ["number",x]}).call(this)},
"percentage":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("m_number");this._applyWithArgs("exactly","%");return ["percentage",x]}).call(this)},
"dimension":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){x=this._apply("number");y=this._apply("m_ident");return ["dimension",x,y]}).call(this)},
"cdo":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._applyWithArgs("exactly","<");this._applyWithArgs("exactly","!");this._applyWithArgs("exactly","-");this._applyWithArgs("exactly","-");"<!--";return ["cdo"]}).call(this)},
"cdc":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._applyWithArgs("exactly","-");this._applyWithArgs("exactly","-");this._applyWithArgs("exactly",">");"-->";return ["cdc"]}).call(this)},
"s":function(){var $elf=this,_fromIdx=this.input.idx,x,xx;return (function(){xx=this._many1((function(){return (function(){x=this._apply("anything");this._applyWithArgs("m_w",x);return x}).call(this)}));return ["s",xx.join("")]}).call(this)},
"attrselector":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=(function(){switch(this._apply('anything')){case "=":return "=";case "~":return (function(){this._applyWithArgs("exactly","=");return "~="}).call(this);case "^":return (function(){this._applyWithArgs("exactly","=");return "^="}).call(this);case "$":return (function(){this._applyWithArgs("exactly","=");return "$="}).call(this);case "*":return (function(){this._applyWithArgs("exactly","=");return "*="}).call(this);default: throw fail}}).call(this);return ["attrselector",x]}).call(this)},
"delim":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._applyWithArgs("exactly",",");return ["delim",","]}).call(this)},
"comment":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","/");this._applyWithArgs("exactly","*");"/*";x=this._many((function(){return (function(){this._not((function(){return (function(){this._applyWithArgs("exactly","*");this._applyWithArgs("exactly","/");return "*/"}).call(this)}));return this._apply("char")}).call(this)}));this._applyWithArgs("exactly","*");this._applyWithArgs("exactly","/");"*/";return ["comment",x.join("")]}).call(this)},
"m_ident":function(){var $elf=this,_fromIdx=this.input.idx,x,y,z;return (function(){x=this._apply("char");this._applyWithArgs("m_nmstart",x);x;z=this._many((function(){return (function(){y=this._apply("anything");this._applyWithArgs("m_nmchar",y);return y}).call(this)}));return (x + z.join(""))}).call(this)},
"m_name":function(){var $elf=this,_fromIdx=this.input.idx,x,xx;return (function(){xx=this._many1((function(){return (function(){x=this._apply("anything");this._applyWithArgs("m_nmchar",x);return x}).call(this)}));return xx.join("")}).call(this)},
"m_number":function(){var $elf=this,_fromIdx=this.input.idx,x,y,x,x;return this._or((function(){return (function(){x=this._many1((function(){return this._apply("digit")}));this._applyWithArgs("exactly",".");y=this._many1((function(){return this._apply("digit")}));return ((x.join("") + ".") + y.join(""))}).call(this)}),(function(){return (function(){switch(this._apply('anything')){case ".":return (function(){x=this._many1((function(){return this._apply("digit")}));return ("." + x.join(""))}).call(this);default: throw fail}}).call(this)}),(function(){return (function(){x=this._many1((function(){return this._apply("digit")}));return x.join("")}).call(this)}))},
"m_string":function(){var $elf=this,_fromIdx=this.input.idx,s,s;return (function(){switch(this._apply('anything')){case "\"":return (function(){s=this._many((function(){return this._or((function(){return this._apply("m_string_nl1")}),(function(){return (function(){this._not((function(){return this._applyWithArgs("exactly","\"")}));return this._apply("char")}).call(this)}))}));this._applyWithArgs("exactly","\"");return (("\"" + s.join("")) + "\"")}).call(this);case "\'":return (function(){s=this._many((function(){return this._or((function(){return this._apply("m_string_nl2")}),(function(){return (function(){this._not((function(){return this._applyWithArgs("exactly","\'")}));return this._apply("char")}).call(this)}))}));this._applyWithArgs("exactly","\'");return (("\'" + s.join("")) + "\'")}).call(this);default: throw fail}}).call(this)},
"m_string_nl1":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=(function(){switch(this._apply('anything')){case "\n":return "\n";case "\r":return "\r";case "\\":return (function(){this._applyWithArgs("exactly","\"");return "\\\""}).call(this);default: throw fail}}).call(this);return x}).call(this)},
"m_string_nl2":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=(function(){switch(this._apply('anything')){case "\n":return "\n";case "\r":return "\r";case "\\":return (function(){this._applyWithArgs("exactly","\'");return "\\\'"}).call(this);default: throw fail}}).call(this);return x}).call(this)},
"m_nmstart":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(CSSBSParser._m_nmstart(x))}).call(this)},
"m_unicode":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(CSSBSParser._m_unicode(x))}).call(this)},
"m_escape":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(CSSBSParser._m_escape(x))}).call(this)},
"m_nmchar":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(CSSBSParser._m_nmchar(x))}).call(this)},
"m_nl":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(CSSBSParser._m_nl(x))}).call(this)},
"m_w":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(CSSBSParser._m_w(x))}).call(this)},
"m_comment":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(CSSBSParser._m_comment(x))}).call(this)}});var CSSParser=exports.CSSParser=objectThatDelegatesTo(CSSBSParser,{
"sc":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("s")}),(function(){return this._apply("comment")}))},
"stylesheet":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._many((function(){return this._or((function(){return this._apply("cdo")}),(function(){return this._apply("cdc")}),(function(){return this._apply("sc")}),(function(){return this._apply("statement")}))}));return this.concat(["stylesheet"],x)}).call(this)},
"statement":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("ruleset")}),(function(){return this._apply("atrule")}))},
"atrulepart":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("sc")}),(function(){return this._apply("any")}),(function(){return this._apply("operator")}))},
"mediaq":function(){var $elf=this,_fromIdx=this.input.idx,ap;return (function(){ap=this._many((function(){return this._apply("atrulepart")}));return ["mediaq"].concat(ap)}).call(this)},
"medias":function(){var $elf=this,_fromIdx=this.input.idx,s0,r,s1;return (function(){s0=this._many((function(){return this._apply("sc")}));r=this._many((function(){return this._apply("ruleset")}));s1=this._many((function(){return this._apply("sc")}));return this.concat(["medias"],s0,r,s1)}).call(this)},
"atrulem":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){this._applyWithArgs("exactly","@");this._applyWithArgs("exactly","m");this._applyWithArgs("exactly","e");this._applyWithArgs("exactly","d");this._applyWithArgs("exactly","i");this._applyWithArgs("exactly","a");"@media";x=this._apply("mediaq");this._applyWithArgs("exactly","{");y=this._apply("medias");this._applyWithArgs("exactly","}");return ["atrulem",x,y]}).call(this)},
"atruleb":function(){var $elf=this,_fromIdx=this.input.idx,ak,ap,b;return (function(){ak=this._apply("atkeyword");ap=this._many((function(){return this._apply("atrulepart")}));b=this._apply("block");return this.concat(["atruleb",ak],ap,[b])}).call(this)},
"atrules":function(){var $elf=this,_fromIdx=this.input.idx,ak,ap;return (function(){ak=this._apply("atkeyword");ap=this._many((function(){return this._apply("atrulepart")}));this._applyWithArgs("exactly",";");return this.concat(["atrules",ak],ap)}).call(this)},
"atrule":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("atrulem")}),(function(){return this._apply("atruleb")}),(function(){return this._apply("atrules")}))},
"blockdecl":function(){var $elf=this,_fromIdx=this.input.idx,s0,x,y,s1,s0,x,s1,s0,x,s1;return this._or((function(){return (function(){s0=this._many((function(){return this._apply("sc")}));x=this._apply("declaration");y=this._apply("decldelim");s1=this._many((function(){return this._apply("sc")}));return this.concat(s0,[x],[y],s1)}).call(this)}),(function(){return (function(){s0=this._many((function(){return this._apply("sc")}));x=this._apply("declaration");s1=this._many((function(){return this._apply("sc")}));return this.concat(s0,[x],s1)}).call(this)}),(function(){return (function(){s0=this._many((function(){return this._apply("sc")}));x=this._apply("decldelim");s1=this._many((function(){return this._apply("sc")}));return this.concat(s0,[x],s1)}).call(this)}))},
"decldelim":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._applyWithArgs("exactly",";");return ["decldelim"]}).call(this)},
"block":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","{");x=this._many((function(){return this._apply("blockdecl")}));this._applyWithArgs("exactly","}");return this.concatContent(["block"],x)}).call(this)},
"ruleset":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){x=this._many((function(){return this._apply("selector")}));y=this._apply("block");return this.concat(["ruleset"],x,[y])}).call(this)},
"combinator":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=(function(){switch(this._apply('anything')){case "+":return "+";case ">":return ">";case "~":return "~";default: throw fail}}).call(this);return ["combinator",x]}).call(this)},
"attrib":function(){var $elf=this,_fromIdx=this.input.idx,s0,x,s1,a,s2,y,s3;return (function(){this._applyWithArgs("exactly","[");s0=this._many((function(){return this._apply("sc")}));x=this._apply("ident");s1=this._many((function(){return this._apply("sc")}));a=this._apply("attrselector");s2=this._many((function(){return this._apply("sc")}));y=this._or((function(){return this._apply("ident")}),(function(){return this._apply("string")}));s3=this._many((function(){return this._apply("sc")}));this._applyWithArgs("exactly","]");return this.concat(["attrib"],s0,[x],s1,[a],s2,[y],s3)}).call(this)},
"class":function(){var $elf=this,_fromIdx=this.input.idx,i;return (function(){this._applyWithArgs("exactly",".");i=this._apply("ident");return ["class",i]}).call(this)},
"pseudoe":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly",":");this._applyWithArgs("exactly",":");"::";x=this._apply("ident");return ["pseudoe",x]}).call(this)},
"pseudoc":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly",":");x=this._or((function(){return this._apply("function")}),(function(){return this._apply("ident")}));return ["pseudoc",x]}).call(this)},
"pseudo":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("pseudoe")}),(function(){return this._apply("pseudoc")}))},
"nthf":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._applyWithArgs("exactly",":");this._applyWithArgs("exactly","n");this._applyWithArgs("exactly","t");this._applyWithArgs("exactly","h");this._applyWithArgs("exactly","-");"nth-";return (function(){switch(this._apply('anything')){case "c":return (function(){this._applyWithArgs("exactly","h");this._applyWithArgs("exactly","i");this._applyWithArgs("exactly","l");this._applyWithArgs("exactly","d");return "child"}).call(this);case "l":return (function(){switch(this._apply('anything')){case "a":return (function(){switch(this._apply('anything')){case "s":return (function(){switch(this._apply('anything')){case "t":return (function(){switch(this._apply('anything')){case "-":return (function(){switch(this._apply('anything')){case "c":return (function(){this._applyWithArgs("exactly","h");this._applyWithArgs("exactly","i");this._applyWithArgs("exactly","l");this._applyWithArgs("exactly","d");return "last-child"}).call(this);case "o":return (function(){this._applyWithArgs("exactly","f");this._applyWithArgs("exactly","-");this._applyWithArgs("exactly","t");this._applyWithArgs("exactly","y");this._applyWithArgs("exactly","p");this._applyWithArgs("exactly","e");return "last-of-type"}).call(this);default: throw fail}}).call(this);default: throw fail}}).call(this);default: throw fail}}).call(this);default: throw fail}}).call(this);default: throw fail}}).call(this);case "o":return (function(){this._applyWithArgs("exactly","f");this._applyWithArgs("exactly","-");this._applyWithArgs("exactly","t");this._applyWithArgs("exactly","y");this._applyWithArgs("exactly","p");this._applyWithArgs("exactly","e");return "of-type"}).call(this);default: throw fail}}).call(this)}).call(this)},
"nth":function(){var $elf=this,_fromIdx=this.input.idx,x,x;return this._or((function(){return (function(){x=this._many1((function(){return this._or((function(){return this._apply("digit")}),(function(){return (function(){switch(this._apply('anything')){case "n":return "n";default: throw fail}}).call(this)}))}));return ["nth",x.join("")]}).call(this)}),(function(){return (function(){x=(function(){switch(this._apply('anything')){case "e":return (function(){this._applyWithArgs("exactly","v");this._applyWithArgs("exactly","e");this._applyWithArgs("exactly","n");return "even"}).call(this);case "o":return (function(){this._applyWithArgs("exactly","d");this._applyWithArgs("exactly","d");return "odd"}).call(this);default: throw fail}}).call(this);return ["nth",x]}).call(this)}))},
"nthselector":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){x=this._apply("nthf");this._applyWithArgs("exactly","(");y=this._many((function(){return this._or((function(){return this._apply("sc")}),(function(){return this._apply("unary")}),(function(){return this._apply("nth")}))}));this._applyWithArgs("exactly",")");return ["nthselector",x].concat(y)}).call(this)},
"simpleselector":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._many1((function(){return this._or((function(){return this._apply("nthselector")}),(function(){return this._apply("combinator")}),(function(){return this._apply("attrib")}),(function(){return this._apply("pseudo")}),(function(){return this._apply("any")}),(function(){return this._apply("sc")}))}));return this.concatContent(["simpleselector"],[x])}).call(this)},
"selector":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._many1((function(){return this._or((function(){return this._apply("simpleselector")}),(function(){return this._apply("delim")}),(function(){return this._apply("sc")}))}));return this.concat(["selector"],x)}).call(this)},
"declaration":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){x=this._apply("property");this._applyWithArgs("exactly",":");y=this._apply("value");return ["declaration",x,y]}).call(this)},
"property":function(){var $elf=this,_fromIdx=this.input.idx,x,s0;return (function(){x=this._apply("ident");s0=this._many((function(){return this._apply("sc")}));return this.concat(["property",x],s0)}).call(this)},
"important":function(){var $elf=this,_fromIdx=this.input.idx,s0;return (function(){this._applyWithArgs("exactly","!");s0=this._many((function(){return this._apply("sc")}));this._applyWithArgs("exactly","i");this._applyWithArgs("exactly","m");this._applyWithArgs("exactly","p");this._applyWithArgs("exactly","o");this._applyWithArgs("exactly","r");this._applyWithArgs("exactly","t");this._applyWithArgs("exactly","a");this._applyWithArgs("exactly","n");this._applyWithArgs("exactly","t");"important";return ["important"].concat(s0)}).call(this)},
"unary":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=(function(){switch(this._apply('anything')){case "-":return "-";case "+":return "+";default: throw fail}}).call(this);return ["unary",x]}).call(this)},
"operator":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=(function(){switch(this._apply('anything')){case "/":return "/";case ",":return ",";case ":":return ":";default: throw fail}}).call(this);return ["operator",x]}).call(this)},
"uri":function(){var $elf=this,_fromIdx=this.input.idx,s0,x,s1,s0,x,s1;return (function(){switch(this._apply('anything')){case "u":return (function(){switch(this._apply('anything')){case "r":return (function(){switch(this._apply('anything')){case "l":return this._or((function(){return (function(){"url";this._applyWithArgs("exactly","(");s0=this._many((function(){return this._apply("sc")}));x=this._apply("string");s1=this._many((function(){return this._apply("sc")}));this._applyWithArgs("exactly",")");return this.concat(["uri"],s0,[x],s1)}).call(this)}),(function(){return (function(){"url";this._applyWithArgs("exactly","(");s0=this._many((function(){return this._apply("sc")}));x=this._many((function(){return (function(){this._not((function(){return this._applyWithArgs("exactly",")")}));this._not((function(){return this._apply("m_w")}));return this._apply("char")}).call(this)}));s1=this._many((function(){return this._apply("sc")}));this._applyWithArgs("exactly",")");return this.concat(["uri"],s0,[["raw",x.join("")]],s1)}).call(this)}));default: throw fail}}).call(this);default: throw fail}}).call(this);default: throw fail}}).call(this)},
"value":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._many1((function(){return this._or((function(){return this._apply("sc")}),(function(){return this._apply("any")}),(function(){return this._apply("block")}),(function(){return this._apply("atkeyword")}),(function(){return this._apply("operator")}),(function(){return this._apply("important")}))}));return this.concat(["value"],x)}).call(this)},
"function":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){x=this._apply("ident");this._applyWithArgs("exactly","(");y=this._many((function(){return this._or((function(){return this._apply("any")}),(function(){return this._apply("sc")}))}));this._applyWithArgs("exactly",")");return this.concat(["function",x],y)}).call(this)},
"braces":function(){var $elf=this,_fromIdx=this.input.idx,s0,x,s1,s0,x,s1;return (function(){switch(this._apply('anything')){case "(":return (function(){s0=this._many((function(){return this._apply("sc")}));x=this._many((function(){return this._apply("any")}));s1=this._many((function(){return this._apply("sc")}));this._applyWithArgs("exactly",")");return this.concat(["braces","(",")"],s0,x,s1)}).call(this);case "[":return (function(){s0=this._many((function(){return this._apply("sc")}));x=this._many((function(){return this._apply("any")}));s1=this._many((function(){return this._apply("sc")}));this._applyWithArgs("exactly","]");return this.concat(["braces","[","]"],s0,x,s1)}).call(this);default: throw fail}}).call(this)},
"jsLT":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){switch(this._apply('anything')){case "\n":return "\n";case "\r":return "\r";default: throw fail}}).call(this)},
"jsComment":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("jsMLComment")}),(function(){return this._apply("jsSLComment")}))},
"jsMLComment":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","/");this._applyWithArgs("exactly","*");"/*";x=this._many((function(){return (function(){this._not((function(){return (function(){this._applyWithArgs("exactly","*");this._applyWithArgs("exactly","/");return "*/"}).call(this)}));return this._apply("char")}).call(this)}));this._applyWithArgs("exactly","*");this._applyWithArgs("exactly","/");"*/";return (("/*" + x.join("")) + "*/")}).call(this)},
"jsSLComment":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","/");this._applyWithArgs("exactly","/");"//";x=this._many((function(){return (function(){this._not((function(){return this._apply("jsLT")}));return this._apply("char")}).call(this)}));return ("//" + x.join(""))}).call(this)},
"jsString":function(){var $elf=this,_fromIdx=this.input.idx,x,x;return (function(){switch(this._apply('anything')){case "\"":return (function(){x=this._many((function(){return this._apply("jsDSChar")}));this._applyWithArgs("exactly","\"");return (("\"" + x.join("")) + "\"")}).call(this);case "\'":return (function(){x=this._many((function(){return this._apply("jsSSChar")}));this._applyWithArgs("exactly","\'");return (("\'" + x.join("")) + "\'")}).call(this);default: throw fail}}).call(this)},
"jsDSChar":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return (function(){this._not((function(){return this._applyWithArgs("exactly","\"")}));this._not((function(){return this._applyWithArgs("exactly","\\")}));this._not((function(){return this._apply("jsLT")}));return this._apply("char")}).call(this)}),(function(){return this._apply("jsEscapeChar")}),(function(){return this._apply("jsLineContinuation")}))},
"jsSSChar":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return (function(){this._not((function(){return this._applyWithArgs("exactly","\'")}));this._not((function(){return this._applyWithArgs("exactly","\\")}));this._not((function(){return this._apply("jsLT")}));return this._apply("char")}).call(this)}),(function(){return this._apply("jsEscapeChar")}),(function(){return this._apply("jsLineContinuation")}))},
"jsLineContinuation":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","\\");x=this._many((function(){return this._apply("jsLT")}));return ("\\" + x.join(""))}).call(this)},
"jsEscapeChar":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","\\");x=this._apply("char");return ("\\" + x)}).call(this)},
"jsInBraceChar":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._not((function(){return this._applyWithArgs("exactly","(")}));this._not((function(){return this._applyWithArgs("exactly",")")}));x=this._apply("char");return x}).call(this)},
"jsBracesContent":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._many1((function(){return this._or((function(){return this._apply("jsComment")}),(function(){return this._apply("jsString")}),(function(){return this._apply("jsEscapeChar")}),(function(){return this._apply("jsInBraceChar")}))}));return x.join("")}).call(this)},
"functionExpressionBody":function(){var $elf=this,_fromIdx=this.input.idx,x,y,z,xx,x,y,z,x;return this._or((function(){return (function(){switch(this._apply('anything')){case "(":return (function(){x=this._many((function(){return this._apply("jsBracesContent")}));xx=this._many((function(){return (function(){y=this._apply("functionExpressionBody");z=this._many((function(){return this._apply("jsBracesContent")}));return (y + z.join(""))}).call(this)}));this._applyWithArgs("exactly",")");return ((("(" + x.join("")) + xx.join("")) + ")")}).call(this);default: throw fail}}).call(this)}),(function(){return (function(){x=this._many((function(){return this._apply("jsBracesContent")}));y=this._apply("functionExpressionBody");z=this._many((function(){return this._apply("jsBracesContent")}));return ((x.join("") + y) + z.join(""))}).call(this)}),(function(){return (function(){x=this._many1((function(){return this._apply("jsBracesContent")}));return x.join("")}).call(this)}))},
"functionExpression":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._applyWithArgs("exactly","e");this._applyWithArgs("exactly","x");this._applyWithArgs("exactly","p");this._applyWithArgs("exactly","r");this._applyWithArgs("exactly","e");this._applyWithArgs("exactly","s");this._applyWithArgs("exactly","s");this._applyWithArgs("exactly","i");this._applyWithArgs("exactly","o");this._applyWithArgs("exactly","n");this._applyWithArgs("exactly","(");"expression(";x=this._many((function(){return this._apply("functionExpressionBody")}));this._applyWithArgs("exactly",")");return ["functionExpression",x.join("")]}).call(this)},
"any":function(){var $elf=this,_fromIdx=this.input.idx,x;return this._or((function(){return (function(){x=this._or((function(){return this._apply("class")}),(function(){return this._apply("string")}),(function(){return this._apply("percentage")}),(function(){return this._apply("dimension")}),(function(){return this._apply("hash")}),(function(){return this._apply("number")}),(function(){return this._apply("uri")}),(function(){return this._apply("functionExpression")}),(function(){return this._apply("function")}),(function(){return this._apply("ident")}),(function(){return this._apply("unary")}));return x}).call(this)}),(function(){return this._apply("braces")}))}});(CSSParser["concatContent"]=(function (x,y){y.forEach((function (e){(x=x.concat(e))}));return x}));(CSSParser["concat"]=(function (){var x = [];for(var i = undefined in arguments){(x=x.concat(arguments[i]))};undefined;return x}))}
var CSSTransformer=exports.CSSTransformer=objectThatDelegatesTo(OMeta,{
"anys":function(){var $elf=this,_fromIdx=this.input.idx;return this._many((function(){return this._apply("any")}))},
"before":function(){var $elf=this,_fromIdx=this.input.idx;return this._form((function(){return undefined}))},
"after":function(){var $elf=this,_fromIdx=this.input.idx;return this._form((function(){return undefined}))},
"any":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("before")}),(function(){return this._apply("ident")}),(function(){return this._apply("atkeyword")}),(function(){return this._apply("string")}),(function(){return this._apply("hash")}),(function(){return this._apply("number")}),(function(){return this._apply("percentage")}),(function(){return this._apply("dimension")}),(function(){return this._apply("cdo")}),(function(){return this._apply("cdc")}),(function(){return this._apply("decldelim")}),(function(){return this._apply("s")}),(function(){return this._apply("attrselector")}),(function(){return this._apply("attrib")}),(function(){return this._apply("nth")}),(function(){return this._apply("nthselector")}),(function(){return this._apply("class")}),(function(){return this._apply("pseudoe")}),(function(){return this._apply("pseudoc")}),(function(){return this._apply("delim")}),(function(){return this._apply("stylesheet")}),(function(){return this._apply("mediaq")}),(function(){return this._apply("medias")}),(function(){return this._apply("atrulem")}),(function(){return this._apply("atruleb")}),(function(){return this._apply("atrules")}),(function(){return this._apply("block")}),(function(){return this._apply("ruleset")}),(function(){return this._apply("combinator")}),(function(){return this._apply("simpleselector")}),(function(){return this._apply("selector")}),(function(){return this._apply("declaration")}),(function(){return this._apply("property")}),(function(){return this._apply("important")}),(function(){return this._apply("unary")}),(function(){return this._apply("operator")}),(function(){return this._apply("braces")}),(function(){return this._apply("value")}),(function(){return this._apply("comment")}),(function(){return this._apply("uri")}),(function(){return this._apply("raw")}),(function(){return this._apply("function")}),(function(){return this._apply("functionExpression")}),(function(){return this._apply("after")}))},
"ident":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","ident");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"atkeyword":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","atkeyword");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"string":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","string");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"hash":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","hash");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"number":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","number");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"percentage":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","percentage");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"dimension":function(){var $elf=this,_fromIdx=this.input.idx,t,x,y;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","dimension");x=this._apply("anything");return y=this._apply("anything")}).call(this)}));return [t,x,y]}).call(this)},
"cdo":function(){var $elf=this,_fromIdx=this.input.idx,t;return (function(){this._form((function(){return t=this._applyWithArgs("exactly","cdo")}));return [t]}).call(this)},
"cdc":function(){var $elf=this,_fromIdx=this.input.idx,t;return (function(){this._form((function(){return t=this._applyWithArgs("exactly","cdc")}));return [t]}).call(this)},
"decldelim":function(){var $elf=this,_fromIdx=this.input.idx,t;return (function(){this._form((function(){return t=this._applyWithArgs("exactly","decldelim")}));return [t]}).call(this)},
"s":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","s");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"attrselector":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","attrselector");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"attrib":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","attrib");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"nth":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","nth");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"nthselector":function(){var $elf=this,_fromIdx=this.input.idx,t,x,y;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","nthselector");x=this._apply("anything");return y=this._apply("anys")}).call(this)}));return [t,x].concat(y)}).call(this)},
"class":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","class");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"pseudoe":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","pseudoe");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"pseudoc":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","pseudoc");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"delim":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","delim");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"stylesheet":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","stylesheet");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"mediaq":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","mediaq");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"medias":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","medias");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"atrulem":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","atrulem");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"atruleb":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","atruleb");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"atrules":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","atrules");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"block":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","block");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"ruleset":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","ruleset");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"combinator":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","combinator");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"simpleselector":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","simpleselector");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"selector":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","selector");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"declaration":function(){var $elf=this,_fromIdx=this.input.idx,t,p,v;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","declaration");p=this._apply("any");return v=this._apply("any")}).call(this)}));return [t,p,v]}).call(this)},
"property":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","property");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"important":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","important");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"unary":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","unary");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"operator":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","operator");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"braces":function(){var $elf=this,_fromIdx=this.input.idx,t,x,y,z;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","braces");x=this._apply("anything");y=this._apply("anything");return z=this._apply("anys")}).call(this)}));return [t,x,y].concat(z)}).call(this)},
"value":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","value");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"comment":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","comment");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"uri":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","uri");return x=this._apply("anys")}).call(this)}));return [t].concat(x)}).call(this)},
"raw":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","raw");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)},
"function":function(){var $elf=this,_fromIdx=this.input.idx,t,x,y;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","function");x=this._apply("anything");return y=this._apply("anys")}).call(this)}));return [t,x].concat(y)}).call(this)},
"functionExpression":function(){var $elf=this,_fromIdx=this.input.idx,t,x;return (function(){this._form((function(){return (function(){t=this._applyWithArgs("exactly","functionExpression");return x=this._apply("anything")}).call(this)}));return [t,x]}).call(this)}})
var CSSTranslator=exports.CSSTranslator=objectThatDelegatesTo(OMeta,{
"anys":function(){var $elf=this,_fromIdx=this.input.idx;return this._many((function(){return this._apply("any")}))},
"before":function(){var $elf=this,_fromIdx=this.input.idx;return this._form((function(){return undefined}))},
"after":function(){var $elf=this,_fromIdx=this.input.idx;return this._form((function(){return undefined}))},
"any":function(){var $elf=this,_fromIdx=this.input.idx;return this._or((function(){return this._apply("before")}),(function(){return this._apply("ident")}),(function(){return this._apply("atkeyword")}),(function(){return this._apply("string")}),(function(){return this._apply("hash")}),(function(){return this._apply("number")}),(function(){return this._apply("percentage")}),(function(){return this._apply("dimension")}),(function(){return this._apply("cdo")}),(function(){return this._apply("cdc")}),(function(){return this._apply("decldelim")}),(function(){return this._apply("s")}),(function(){return this._apply("attrselector")}),(function(){return this._apply("attrib")}),(function(){return this._apply("nth")}),(function(){return this._apply("nthselector")}),(function(){return this._apply("class")}),(function(){return this._apply("pseudoe")}),(function(){return this._apply("pseudoc")}),(function(){return this._apply("delim")}),(function(){return this._apply("stylesheet")}),(function(){return this._apply("mediaq")}),(function(){return this._apply("medias")}),(function(){return this._apply("atrulem")}),(function(){return this._apply("atruleb")}),(function(){return this._apply("atrules")}),(function(){return this._apply("block")}),(function(){return this._apply("ruleset")}),(function(){return this._apply("combinator")}),(function(){return this._apply("simpleselector")}),(function(){return this._apply("selector")}),(function(){return this._apply("declaration")}),(function(){return this._apply("property")}),(function(){return this._apply("important")}),(function(){return this._apply("unary")}),(function(){return this._apply("operator")}),(function(){return this._apply("braces")}),(function(){return this._apply("value")}),(function(){return this._apply("comment")}),(function(){return this._apply("uri")}),(function(){return this._apply("raw")}),(function(){return this._apply("function")}),(function(){return this._apply("functionExpression")}),(function(){return this._apply("after")}))},
"ident":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","ident");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"atkeyword":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","atkeyword");return x=this._apply("anything")}).call(this)}));return ("@" + x)}).call(this)},
"string":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","string");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"hash":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","hash");return x=this._apply("anything")}).call(this)}));return ("#" + x)}).call(this)},
"number":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","number");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"percentage":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","percentage");return x=this._apply("anything")}).call(this)}));return (x + "%")}).call(this)},
"dimension":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","dimension");x=this._apply("any");return y=this._apply("anything")}).call(this)}));return (x + y)}).call(this)},
"cdo":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._form((function(){return this._applyWithArgs("exactly","cdo")}));return "<!--"}).call(this)},
"cdc":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._form((function(){return this._applyWithArgs("exactly","cdc")}));return "-->"}).call(this)},
"decldelim":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){this._form((function(){return this._applyWithArgs("exactly","decldelim")}));return ";"}).call(this)},
"s":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","s");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"attrselector":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","attrselector");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"attrib":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","attrib");return x=this._apply("anys")}).call(this)}));return (("[" + x.join("")) + "]")}).call(this)},
"nth":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","nth");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"nthselector":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","nthselector");x=this._apply("anything");return y=this._apply("anys")}).call(this)}));return ((((":nth-" + x) + "(") + y.join("")) + ")")}).call(this)},
"class":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","class");return x=this._apply("any")}).call(this)}));return ("." + x)}).call(this)},
"pseudoe":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","pseudoe");return x=this._apply("anys")}).call(this)}));return ("::" + x.join(""))}).call(this)},
"pseudoc":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","pseudoc");return x=this._apply("anys")}).call(this)}));return (":" + x.join(""))}).call(this)},
"delim":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","delim");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"stylesheet":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","stylesheet");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"mediaq":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","mediaq");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"medias":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","medias");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"atrulem":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","atrulem");x=this._apply("any");return y=this._apply("any")}).call(this)}));return (((("@media" + x) + "{") + y) + "}")}).call(this)},
"atruleb":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","atruleb");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"atrules":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","atrules");return x=this._apply("anys")}).call(this)}));return (x.join("") + ";")}).call(this)},
"block":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","block");return x=this._apply("anys")}).call(this)}));return (("{" + x.join("")) + "}")}).call(this)},
"ruleset":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","ruleset");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"combinator":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","combinator");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"simpleselector":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","simpleselector");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"selector":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","selector");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"declaration":function(){var $elf=this,_fromIdx=this.input.idx,p,v;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","declaration");p=this._apply("any");return v=this._apply("any")}).call(this)}));return ((p + ":") + v)}).call(this)},
"property":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","property");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"important":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","important");return x=this._apply("anys")}).call(this)}));return (("!" + x.join("")) + "important")}).call(this)},
"unary":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","unary");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"operator":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","operator");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"braces":function(){var $elf=this,_fromIdx=this.input.idx,x,y,z;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","braces");x=this._apply("anything");y=this._apply("anything");return z=this._apply("anys")}).call(this)}));return ((x + z.join("")) + y)}).call(this)},
"value":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","value");return x=this._apply("anys")}).call(this)}));return x.join("")}).call(this)},
"comment":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","comment");return x=this._apply("anything")}).call(this)}));return (("/*" + x) + "*/")}).call(this)},
"uri":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","uri");return x=this._apply("anys")}).call(this)}));return (("url(" + x.join("")) + ")")}).call(this)},
"raw":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","raw");return x=this._apply("anything")}).call(this)}));return x}).call(this)},
"function":function(){var $elf=this,_fromIdx=this.input.idx,x,y;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","function");x=this._apply("any");return y=this._apply("anys")}).call(this)}));return (((x + "(") + y.join("")) + ")")}).call(this)},
"functionExpression":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","functionExpression");return x=this._apply("anything")}).call(this)}));return (("expression(" + x) + ")")}).call(this)}})
// CSS 2.1 / 4.1.1 Tokenization / macro section

// [_a-z]|{nonascii}|{escape}
CSSBSParser['_m_nmstart'] = function(x) {
    return /[_a-zA-Z\-\*]/.test(x) || CSSBSParser['_m_escape'](x);
};

// \\[0-9a-f]{1,6}(\r\n|[ \n\r\t\f])?
CSSBSParser['_m_unicode'] = function(x) {
    return /\\[0-9a-fA-F]{1,6}(\r\n|[ \n\r\t\f])?/.test(x);
};

// {unicode}|\\[^\n\r\f0-9a-f]
CSSBSParser['_m_escape'] = function(x) {
    return CSSBSParser['_m_unicode'](x) || /\\[^\n\r\f0-9a-fA-F]/.test(x);
}

// [_a-z0-9-]|{nonascii}|{escape}
CSSBSParser['_m_nmchar'] = function(x) {
    return /[_a-zA-Z0-9\-]/.test(x) || CSSBSParser['_m_escape'](x);
};

//  \n|\r\n|\r|\f
CSSBSParser['_m_nl'] = function(x) {
    return /[ \n\r\n\r\f]/.test(x);
};

// [ \t\r\n\f]*
CSSBSParser['_m_w'] = function(x) {
    return /[ \t\r\n\f]/.test(x);
};

// \/\*[^*]*\*+([^/*][^*]*\*+)*\/
CSSBSParser['_m_comment'] = function(x) {
    return new RegExp('\/\*[^*]*\*+([^/*][^*]*\*+)*\/').test(x);
};

